### ISSUE TITLE
PYPI version cannot be installed 

### ISSUE THREAD

**Issue by dapangmao** [vicalloy/LBForum#30]
There is an error while installing with pip

```
Collecting lbforum
  Using cached LBForum-2.0.0.tar.gz
Collecting Django==1.10 (from lbforum)
  Using cached Django-1.10-py2.py3-none-any.whl
Collecting django-el-pagination==3.0.1 (from lbforum)
  Using cached django-el-pagination-3.0.1.tar.gz
Collecting easy_thumbnails==2.3 (from lbforum)
  Using cached easy_thumbnails-2.3-py2.py3-none-any.whl
Collecting beautifulsoup4==4.5.1 (from lbforum)
  Using cached beautifulsoup4-4.5.1-py3-none-any.whl
Collecting BeautifulSoup==3.2.1 (from lbforum)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hygkh21d/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
```
I believe it is due to the two `beautifulsoup`s from the `setup.py` file of the PYPI version.
```
install_requires = [
    'Django==1.10',
    'django-el-pagination==3.0.1',
    'easy_thumbnails==2.3',
    'beautifulsoup4==4.5.1',
    'BeautifulSoup==3.2.1',
    'python-dateutil==2.5.3',
    'django-constance==1.2',
    'django_picklefield==0.3.2',
    'django-lbattachment==1.0.2',
    'django-lbutils==1.0.1',
    'djangorestframework==3.4.6',
]
```

**Comment by vicalloy** [comment]
PYPI updated.
